### ISSUE TITLE
Some Questions 

### ISSUE THREAD

**Issue by cookieSN** [gsl12/Tiny-M#1]
Hi, 

before I ask my question, I would like to tell you, that I find your variant of the Voron V0 very cool.  

I like the standard voron v0, but the few centimeters more make a huge difference.  Many thanks for your effort.

My question: 

Did you only add 30mm to the original for the aluminum extrusion?  (Example: 200mm (voron v0) + 30mm) 

Are you thinking to provide a bom (e.g. based on the voron v0 bom)?  

Thank you and regards, 

CookieSN

**Comment by gsl12** [comment]
Hello ,

to your first question. 

At the beginning this printer was planned as a small version of a Voron 1.6 with linear rails. So the extrusion lenght was get from the calculator at vorondesign.com for a size of 120x120x130. The goal was not to get a specific build size, but a fixed outside dimension for the frame of 300x300x300mm. Later the V0 was released and i desided to switch to the V0 design. The good point was , that i recognized that with the V0 design a build size o 150x150x150 was possible with extrusions i already had. 

to your second question.

I'm working on a BOM at the moment. Onshape has this feature included, some parts are still missing and some parts(like printed part) are not excluded from the BOM in Onshape. Later i will put a excel sheet here. 

This is my first project of this kind. Maybe something will be missing, is not well documented, or just messy. I apologize for that.

best regards

GSL12

**Comment by cookieSN** [comment]
Hi, 

thank you for the quick and comprehensive answer to the questions.  

If you need support, just let me know.  Maybe I can help.  

I will definitely build your variant of the Voron and look forward to your bom.  

Do you use discord?  

Best regards from Germany, 

cookieSN

**Comment by gsl12** [comment]
Yes i use discord. Username same as here.

**Comment by BTopbas** [comment]
Thanks for your amazing work! Bom is when will be available?

**Comment by cookieSN** [comment]
> Thanks for your amazing work! Bom is when will be available?

Hi, I am working on the BOM. So, maybe end of this week.

**Comment by hhammarstrand** [comment]
Another question related to the BOM; can the Tiny-M be built from 2020 V-slot?

**Comment by cookieSN** [comment]
Hi guys, 

sorry that it took a little longer. 

I have attached the BOM to this post, but it is not final yet. The links to the sources (local source, AliExpress, etc.) are still missing. I'll upload an updated version on Sunday. When designing, I stuck to the original BOM from the Voron V0. 

If you want any changes, just let me know.
[DRAFT - BOM - Tiny M.xlsx](https://github.com/gsl12/Tiny-M/files/5235476/DRAFT.-.BOM.-.Tiny.M.xlsx)

**Comment by hhammarstrand** [comment]
@cookieSN Thank you! 

@gsl12 Do you know if it's possible to build the T-M with v-slot extrusions? I have some left from my old printer and it would be nice to be able to use them

**Comment by gsl12** [comment]
@hhammarstrand 
Because of the MGN9 the Tiny-M has the same restrictions as every other Voron. V-Slot was not recommended while the Nut is to big. MGN9 is 9mm width and Mitsumi Profile's nut is 6mm. The nut of the profiles i use is 5mm. 
I'm not sure but the widthest point for the V-slot is 9.2mm, so you can't get the right position for the MGN9 rails.

**Comment by hhammarstrand** [comment]
@gsl12 Thank you for the information. I will have to find another use for the v-slot then. The plan is to build a Tiny-M when I'm done with my Switchwire.
