### ISSUE TITLE
The E3D V6 print head doesn't fit, it's too tight

### ISSUE THREAD

**Issue by shenwrt** [gsl12/Tiny-M#2]
Hello, thank you very much for your sharing, but I found that there is no model of E3D V6 in the file ".step", and the ".STL "can't be installed after it is printed directly, because it is too tight.I need your help. Could you please share the "step" file containing E3D V6? Thank you very much

**Comment by shenwrt** [comment]
Google translation, please forgive me for my poor English

**Comment by gsl12** [comment]
Can you try to use the onshape source files. I'm on vacation at the moment. Otherwise you will need to wait some days.

**Comment by shenwrt** [comment]
Ok, I'll try. Thank you

**Comment by gsl12** [comment]
I  added the cad file for E3Dv6 x-carriage.
