### ISSUE TITLE
Why 0.9 steppers?

### ISSUE THREAD

**Issue by VICLER** [gsl12/Tiny-M#23]
Hi @gsl12! Thanks for sharing your work!
I am actually searching and ordering parts for building my Tiny-M and I have some nema17 48mm motors with 1.8deg I wanted to use. In your BOM you recommend 0.9deg motor. Is there any print quality improvements with 0.9 instead of 1.8, or why is it recommended? Usually, 1.8deg motor has more torque than 0.9deg motor of the same size.

**Comment by properlypurple** [comment]
@VICLER You can use 1.8, lots of us do. There is some discussion about this on Discord as well.

In general, 1.8 is good for speed, and 0.9 is slightly better for quality. You can get high torque 0.9 motors from LDO. I use 1.8 from a local manufacturer and they work fine.(mainly, go for what you can get easily)

**Comment by VICLER** [comment]
thanks for this info!
