### ISSUE TITLE
Is there a modified version of "maybe_tophat.stl"

### ISSUE THREAD

**Issue by shenwrt** [gsl12/Tiny-M#3]
Is there a modified version of "maybe_tophat.stl",
Thank you and regards

**Comment by gsl12** [comment]
No, i only print PLA or PETG with this printer, so i didn't plan to enclosure it.

**Comment by BTopbas** [comment]
Enclosure and tophat mod will be great...

**Comment by optizyme** [comment]
https://www.prusaprinters.org/prints/64115-tiny-m-voron0-mod-tophead
Not sure if it will work or not for you. Seems ok to me.

**Comment by CroXY3D** [comment]
linked to this tophat in the readme.   Official tophat is in development and released soon.
