### ISSUE TITLE
tiny-m differences? 

### ISSUE THREAD

**Issue by Bluesandbox** [gsl12/Tiny-M#4]
How different is the assembly/parts of the tiny-m mod compared to the normal voron 0, are all the parts/lengths the same, just thicker extrusions and different rails with different printed parts? and it uses mgn12 blocks and not mgn12c or mgn12h (and mgn9 and not mgn9h or mgn9c) correct?

**Comment by gsl12** [comment]
The building steps are the same as for a normal V0. 
Tiny-m is bigger then the normal V0. Normal V0 has a build size of 120mm³ the tiny-m has 150mm³. 
For MGN please use the H blocks, like in every other Voron. C blocks are shorter then H and cannot used.
