### ISSUE TITLE
Using Prusa Mini Heated Bed

### ISSUE THREAD

**Issue by BTopbas** [gsl12/Tiny-M#5]
I want to build Tiny-M. I checked the step file and thinking to change the bed with Prusa mini bed and carriage. I need to increase the distance between bed support extrusions a little. And need some little modifications to these parts. This is meehh okay why not idea or wtf terrible idea? Here are my simulations.. (I am not professional with f360.)

![image0](https://user-images.githubusercontent.com/6390054/93717280-79225b80-fb7d-11ea-8f09-f81623129d17.JPG)
![image1](https://user-images.githubusercontent.com/6390054/93717271-6c056c80-fb7d-11ea-96ab-06fc3d423b99.JPG)

**Comment by gsl12** [comment]
I'm not sure if this will be a good or bad idea. 
Problems i see: 
You will lost z endstop and you will need to find another solution(position).
You will never reach each end of the bed. Prusa mini bed is 18x18cm. Tiny-M is for 15x15cm.

**Comment by wesc23** [comment]
If you get this working, we can put the modified STLs in the new usermods directory here.

**Comment by isulpt** [comment]
Any news about that? I have a prusa mini and interested in build a tiny-M with prusa bed.

**Comment by wesc23** [comment]
There's a 180mm bed mod in the works.     Join the discord channel to see progress.
