### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by hunterius-prime** [gsl12/Tiny-M#8]
I was searching to contact @gsl12 directly but didn't find any contact , is it possible?
And side question: under what license is this work distributed? ( I can't find any license file or mention)

**Comment by gsl12** [comment]
You can reach me on discord. The license is GPLv3 , because this is a fork of a Voron V0.

**Comment by CroXY3D** [comment]
Discord is here: https://discord.gg/tmZkjWs
